steps:
  - id: packer_build_external
    name: "us-west1-docker.pkg.dev/gep-kne/packer/packer"
    args: ["build", "cloudbuild/external.pkr.hcl"]
    env: [
      "PKR_VAR_build_id=$BUILD_ID",
      "PKR_VAR_short_sha=$SHORT_SHA",
      "PKR_VAR_branch_name=$BRANCH_NAME",
      "PKR_VAR_zone=${_ZONE}",
    ]

  - id: packer_build_internal
    name: "us-west1-docker.pkg.dev/gep-kne/packer/packer"
    args: ["build", "cloudbuild/internal.pkr.hcl"]
    env: [
      "PKR_VAR_build_id=$BUILD_ID",
      "PKR_VAR_short_sha=$SHORT_SHA",
      "PKR_VAR_branch_name=$BRANCH_NAME",
      "PKR_VAR_zone=${_ZONE}",
    ]
    waitFor: ["-"] # run the builds concurrently

timeout: 1800s

substitutions:
  _ZONE: us-central1-b # default value

options:
  pool:
    name: "projects/gep-kne/locations/us-central1/workerPools/kne-cloudbuild-pool"
