apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "kne-assembly-webhook.kne.org"
webhooks:
  - name: "kne-assembly-webhook.kne.org"
    namespaceSelector:
      matchLabels:
        kne-topology: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: kne-assembly-webhook
        path: /mutate-objects
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPVENDQWlHZ0F3SUJBZ0lVRFBMb2FqV1NL
        Vzd2R2k0blQ3bkxQbkJSZW5Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERUxNQWtHQTFVRUJoTUNR
        VlV4SFRBYkJnTlZCQU1NRkd0dVpTMWhjM05sYldKc2VTMTNaV0pvYjI5cgpNQjRYRFRJME1EUXdN
        akl4TVRnME1Gb1hEVEkxTURRd01qSXhNVGcwTUZvd0xERUxNQWtHQTFVRUJoTUNRVlV4CkhUQWJC
        Z05WQkFNTUZHdHVaUzFoYzNObGJXSnNlUzEzWldKb2IyOXJNSUlCSWpBTkJna3Foa2lHOXcwQkFR
        RUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUFuL0lQb2xuZEx2b3FVejRjMUt6a3RLVFBPZzc5eG5IYTc0
        ZGFJZWU4enFaUwpmMjlMRmk0R1FRT0EwaStmNDJvOVdPK2UwTFY5VTV1eHhOWVpkL2Q4WnJrU295
        Q2RtYnhqeFduZFduOUY1cVE5ClZZQ05jaGNVcnJQamJPK1c0dVcwZlRCUmo3SGd0RktTOFRGZXBo
        a0x2Yjd5VWJZUldlZ3dXUStyQTdjQ3JGd1UKemI4ZFBXT2xTRzQyVXhaekM5aDZGbzkxM09IVzdX
        a0E5MTg2S0IycE1pQlNDcHhwb1d1cW5NVk9ndWR3bWpqZgpEaC80K2xhWkNDTThLbk5Ca3NhNGQw
        czJiQXhCaVFtR2grWk5vUHV2c2xiYWhMakVreDYzR2hDc1lhWUZMWUhxCk00UWg1T0ZLZWgvMVYz
        SUNOV2dHa1BHQVlRalRIOU5VTVB5eTlONlIwUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEUKRmdRVWpM
        OUxtZHp0bzNhcEQ5Tm41UFMxRUs2TThLWXdId1lEVlIwakJCZ3dGb0FVakw5TG1kenRvM2FwRDlO
        bgo1UFMxRUs2TThLWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFP
        Q0FRRUFjMFNyCnNuZ29ka2I3WUx1QnBZMHZ6L2VybkFQM08xK1F2VmdZUGtRU1NjbkhyVXBrQUo1
        UnR4Mk4xemxQQm1kdXJqNUwKSEx5N3hmR002R0hDR1FBNGtGZG13dDdaME9qVUVBQ0hvSzNPWHRX
        cGY4bWdzb243WmVDOG1XUDlWbS9SdElmNworKzJVdVgvSkk5TkN0dlhDYVQzS21CTWtna3ZxWUMw
        M0RKUlVtWUo1OVNscVA2TmNGcTZBcGRyZCtBazNvcy9pCkhjT2ZyU0Y3dEpZdFQxZzBiT2hXbDNQ
        SmpMSTIvWWxTcm0yTXRrQkpuWTJYNldUV2Y2Y0RhcVNjc3hOaWl5N08KYmdCMFpmcDdvVnp5dWhv
        ZVVjV2lXRUJIY1BkZGI5Q0VEeW0yamZ4V2NUWWhiRitGaHM0LzhndHBLY3lRWVZCRgo0Z2o3SCsv
        bFlnOCtsZHNJa1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
