# external.yaml cluster config file sets up ingress, cni, and controllers in an existing k8 cluster.
# The "external" cluster lifecycle is not managed by the KNE deployment.
cluster:
  kind: External
ingress:
  kind: MetalLB
  spec:
    manifest: ../../manifests/metallb/manifest.yaml
    ip_count: 100
cni:
  kind: Meshnet
  spec:
    manifest: ../../manifests/meshnet/grpc/manifest.yaml
controllers:
  - kind: IxiaTG
    spec:
      operator: ../../manifests/keysight/ixiatg-operator.yaml
      configMap: ../../manifests/keysight/ixiatg-configmap.yaml
  - kind: SRLinux
    spec:
      operator: ../../manifests/controllers/srlinux/manifest.yaml
  - kind: CEOSLab
    spec:
      operator: ../../manifests/controllers/ceoslab/manifest.yaml
  - kind: Lemming
    spec:
      operator: ../../manifests/controllers/lemming/manifest.yaml
