# kind-bridge.yaml cluster config file sets up a kind cluster where default PTP CNI plugin
# is swapped with the Bridge CNI plugin.
# Bridge CNI plugin is required by some Network OSes to operate.
cluster:
  kind: Kind
  spec:
    name: kne
    recycle: True
    version: v0.17.0
    image: kindest/node:v1.26.0
    config: ../../kind/kind-no-cni.yaml
    additionalManifests:
      - ../../manifests/kind/kind-bridge.yaml
ingress:
  kind: MetalLB
  spec:
    manifests: ../../manifests/metallb
    ip_count: 100
cni:
  kind: Meshnet
  spec:
    manifests: ../../manifests/meshnet/grpc
controllers:
  - kind: IxiaTG
    spec:
      manifests: ../../manifests/keysight
  - kind: SRLinux
    spec:
      manifests: ../../manifests/controllers/srlinux
  - kind: CEOSLab
    spec:
      manifests: ../../manifests/controllers/ceoslab
