cluster:
  kind: Kind
  spec:
    name: knetest
    recycle: True
    version: v0.14.0
    image: kindest/node:v1.24.3
ingress:
  kind: MetalLB
  spec:
    manifests: ../../manifests/metallb
    ip_count: 100
cni:
  kind: Meshnet
  spec:
    manifests: ../../manifests/meshnet/base
