apiVersion: v1
kind: ConfigMap
metadata:
  name: ixiatg-release-config
  namespace: ixiatg-op-system
data:
  versions: |
    {
      "release": "0.0.1-9999",
      "images": [
            {
                "name": "controller",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-controller",
                "tag": "0.0.1-4399"
            },
            {
                "name": "gnmi-server",
                "path": "ghcr.io/open-traffic-generator/ixia-c-gnmi-server",
                "tag": "1.12.2"
            },
            {
                "name": "traffic-engine",
                "path": "ghcr.io/open-traffic-generator/ixia-c-traffic-engine",
                "tag": "1.6.0.35"
            },
            {
                "name": "protocol-engine",
                "path": "ghcr.io/open-traffic-generator/licensed/ixia-c-protocol-engine",
                "tag": "1.00.0.320"
            },
            {
                "name": "ixhw-server",
                "path": "ghcr.io/open-traffic-generator/ixia-c-ixhw-server",
                "tag": "0.12.1-2"
            }
        ]
    }
