# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# this namespace resource is created separately to support
# license secrets to be created with a namespace provisioned automatically
# if srl controller is created first, then this namespace will be already created
# as part of the manager kustomization.
resources:
  - "namespace.yml"
