---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@e83596f1c217a055744a49a584223cecee7c0891
    with:
      coverage-excludes-regex: /cloudbuild
      tests-excludes-regex: /cloudbuild
      skip-race-tests: true
      go-versions: "['1.20']"

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@e83596f1c217a055744a49a584223cecee7c0891
