---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@acc15986a7611306329c6c9deded8cd70603173b
    with:
      coverage-excludes-regex: /cloudbuild
      tests-excludes-regex: /cloudbuild
      race-tests-excludes-regex: /cloudbuild
      skip-race-tests: true
      go-versions: "['1.20']"

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@acc15986a7611306329c6c9deded8cd70603173b
