---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  common:
    uses: openconfig/common-ci/.github/workflows/go.yml@76502bf561a6c37d85d93395f5fd1044f1afc994
    with:
      coverage-excludes-regex: /cloudbuild
      tests-excludes-regex: /cloudbuild
      race-tests-excludes-regex: /cloudbuild
      go-versions: "['1.20']"
