---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@6b5a0aca49a63cd0d32129c6a2c3e1cc07b7f949
    with:
      coverage-excludes-regex: /cloudbuild
      tests-excludes-regex: /cloudbuild
      race-tests-excludes-regex: /cloudbuild
      skip-race-tests: true
      go-versions: "['1.21']"

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@6b5a0aca49a63cd0d32129c6a2c3e1cc07b7f949
