---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/go.yml@125b6b58286d116b216e45c33cb859f547965d61
    with:
      coverage-excludes-regex: /cloudbuild
      tests-excludes-regex: /cloudbuild
      race-tests-excludes-regex: /cloudbuild
      skip-race-tests: true
      go-versions: "['1.21']"

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@125b6b58286d116b216e45c33cb859f547965d61
